[build]
  publish = "./site"
  command = """
pip install --upgrade pip;
pip install mkdocs mkdocs-awesome-nav mkdocs-material mkdocs-redirects mkdocs-static-i18n;
bash hack/internationalize.sh /opt/build/repo --netlify;
echo '*** BEGIN /opt/build/repo/mkdocs.yml ***';
cat /opt/build/repo/mkdocs.yml;
echo '*** END /opt/build/repo/mkdocs.yml ***';
python -m mkdocs build -f /opt/build/repo/mkdocs.yml -d /opt/build/repo/site
"""
