[[creating-template-wizard-web]]
== Creating a Virtual Machine Template with the Interactive Wizard

Virtual machine templates are an easy way to create multiple virtual machines with similar configuration. After a template is created, reference the template when xref:creating-vm-wizard-web[creating virtual machines].

The web console features an interactive wizard that guides you through xref:template-wizard-fields-web[*Basic Settings*], xref:networking-wizard-fields-web[*Networking*], and xref:storage-wizard-fields-web[*Storage*] screens to simplify the process of creating virtual machine templates. All required fields are marked with a `*`. The wizard prevents you from moving to the next screen until the required fields have been completed.

NICs and storage disks can be created and attached to virtual machines after they have been created.

.*Bootable Disk*

If either `URL` or `Container` are selected as the *Provision Source* in the xref:template-wizard-fields-web[*Basic Settings*] screen, a `rootdisk` disk is created and attached to virtual machines as the *Bootable Disk*. You can modify the `rootdisk` but you cannot remove it.

A *Bootable Disk* is not required for virtual machines provisioned from a *PXE* source if there are no disks attached to the virtual machine. If one or more disks are attached to the virtual machine, you must select one as the *Bootable Disk*.

.Procedure

. Click *Workloads* -> *Virtual Machine Templates* from the side menu.
. Click *Create Template* and select *Create with Wizard*.
. Fill in all required xref:template-wizard-fields-web[*Basic Settings*].
. Click *Next* to progress to the xref:networking-wizard-fields-web[*Networking*] screen. An `nic0` NIC is attached by default.
.. (Optional) Click *Create NIC* to create additional NICs.
.. (Optional) You can remove any or all NICs by clicking the &#8942; button and selecting *Remove NIC*. Virtual machines created from a template do not need a NIC attached. NICs can be xref:vm-create-nic-web[created] after a virtual machine has been created.
. Click *Next* to progress to the xref:storage-wizard-fields-web[*Storage*] screen.
.. (Optional) Click *Create Disk* to create additional disks. These disks can be removed by clicking the &#8942; button and selecting *Remove Disk*.
.. (Optional) Click on a disk to modify available fields. Click the &#10003; button to save the update.
.. (Optional) Click *Attach Disk* to choose an available disk from the *Select Storage* drop-down list.
. Click *Create Virtual Machine Template >*. The *Results* screen displays the JSON configuration file for the virtual machine template.

The template should now be listed in *Workloads* -> *Virtual Machine Templates*.