[[editing-vm-yaml-web]]
== Editing the YAML of a Virtual Machine

You can edit the YAML configuration of a virtual machine directly within the web console.

Not all parameters can be updated. If you edit values that cannot be changed and click *Save*, an error message indicates the parameter that was not able to be updated.

The YAML configuration can be edited while the virtual machine is *Running*, however the changes will only take effect after the virtual machine has been restarted.

________________________
Note: Navigating away from the YAML screen while editing cancels any changes to the configuration you have made.
________________________

.Procedure

. Click *Workloads* -> *Virtual Machine* from the side menu.
. Select a virtual machine.
. Click the *YAML* tab to display the editable configuration.
.. (Optional) You can click *Download* to download the YAML file to your local machine in its current state.
. Edit the file and click *Save*.

A confirmation message shows that the modification has been successful, including the updated version number for the object.