nav:
  - Welcome: en/welcome.md
  - Architecture: en/architecture.md
  - Quickstarts: en/quickstarts.md
  - Cluster Administration: en/cluster_admin
  - User Workloads: en/user_workloads
  - Compute: en/compute
  - Network: en/network
  - Storage: en/storage
  - Release Notes: en/release_notes.md
  - Contribute: en/contributing.md
  - Virtualization Debugging: en/debug_virt_stack
